### ISSUE TITLE
No License Specified

### ISSUE THREAD

**Issue by dlevineBC** [ongov/Service-Design-Playbook#3]
We'd like to potentially use some of this content for the BC government guidance, but there is no licensing associated to this repo. Having an understanding of your licensing would enable the sharing and re-use of this awesome content.

For reference, our Github repos are published under the Creative Commons Attribution 4.0 International Public License

**Comment by jeramin** [comment]
Hi, thanks for flagging this! We'll get started with adding a license.

**Comment by jeramin** [comment]
Hello, sorry for the delay, the license has been added!
